name: Build LaTeX And push .pdf
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
#      - name: Mover archivos
#        run: |
#          mv umemoria.cls ~/texmf/tex/latex/local/
#          mv escudou.pdf ~/texmf/tex/latex/local/
#          maketexlsr
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: memoria.tex
        env:
          TEXINPUTS: ".:./:"
      # src: https://github.community/t/possible-to-commit-files-after-workflow-runs/17824/2
      - name: move to dir # Move the generated files into output folder
        run: |
          mkdir -p output
          yes| cp -rf memoria.pdf ./
      - name: Commit files # commit the output folder
        run: |
          git config --local user.email "diego.irarrazaval@ug.uchile.cl"
          git config --local user.name "Diego-II"
          git add ./memoria.pdf
          git commit -m "Subir compilado en PDF"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          #branch: B77 #ignore if your branch is master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
